// Custom Cloudflare Worker entry for Souk El Gomla.
//
// Wraps the OpenNext-generated worker (`.open-next/worker.js`) so we can add a
// `scheduled` handler for the social-feed auto-sync cron trigger. The default
// `fetch` simply delegates to OpenNext.
//
// The `scheduled` handler invokes the internal sync endpoint
// (`/api/internal/social-sync`) with the shared CRON_SECRET. We deliberately
// do NOT import the app's TypeScript modules here: this entry is bundled by
// wrangler's own esbuild, which has no access to the project's `@/` path
// aliases. The internal route (bundled by Next/OpenNext) runs the real sync, so
// bindings (D1/KV/secrets) resolve identically to a normal request.

//@ts-expect-error: Resolved by wrangler build (generated by opennextjs/cloudflare).
import opennextHandler from ".open-next/worker.js";

// The cron expression that triggers the social feed sync (must match
// `triggers.crons` in wrangler.jsonc). All configured crons invoke this
// handler, so we gate on the exact expression.
const SOCIAL_SYNC_CRON = "*/30 * * * *";

export default {
  async fetch(request, env, ctx) {
    return opennextHandler.fetch(request, env, ctx);
  },

  async scheduled(event, env, ctx) {
    if (event.cron !== SOCIAL_SYNC_CRON) {
      return;
    }
    const baseUrl = env.NEXT_PUBLIC_APP_URL || "https://souqelgomala.m-2396.workers.dev";
    const secret = env.CRON_SECRET;
    if (!secret) {
      console.error("[scheduled] CRON_SECRET not set; skipping social sync");
      return;
    }
    const url = `${baseUrl.replace(/\/$/, "")}/api/internal/social-sync`;
    ctx.waitUntil(
      fetch(url, {
        method: "POST",
        headers: { "content-type": "application/json", "x-cron-secret": secret },
      })
        .then((res) => console.log("[scheduled] social sync status", res.status))
        .catch((err) => console.error("[scheduled] social sync failed", err))
    );
  },
};
