-- ============================================================
-- Generated by scripts/seed-admin.ts — first OWNER account
-- Apply with: wrangler d1 execute DB --file=<this file>
-- ============================================================

-- 1) Insert the account if the email does not exist yet.
INSERT OR IGNORE INTO profiles (id, email, password_hash, full_name, phone, role, avatar, branch_id, is_active, created_at, updated_at)
VALUES ('937b11dd-e5b9-4765-8f7c-10fbe8e20353', 'marawan1@example.com', 'ZExzFbOOleWgmTWDm50yn7O7MYh+KKV+ITXZDu7AFC1pQIMY4E5aIGMQomh88oVq', 'System Owner', NULL, 'owner', NULL, '00000000-0000-0000-0000-000000000001', 1, '2026-08-09T13:32:26.125Z', '2026-08-09T13:32:26.125Z');

-- 2) Refresh the password/role whenever the script is re-run.
UPDATE profiles
SET password_hash = 'ZExzFbOOleWgmTWDm50yn7O7MYh+KKV+ITXZDu7AFC1pQIMY4E5aIGMQomh88oVq', role = 'owner', is_active = 1, updated_at = '2026-08-09T13:32:26.125Z', full_name = 'System Owner'
WHERE email = 'marawan1@example.com';
