-- ============================================================
-- Generated by scripts/seed-admin.ts — first OWNER account
-- Apply with: wrangler d1 execute DB --file=<this file>
-- ============================================================

-- 1) Insert the account if the email does not exist yet.
INSERT OR IGNORE INTO profiles (id, email, password_hash, full_name, phone, role, avatar, branch_id, is_active, created_at, updated_at)
VALUES ('624104a4-7b68-4a05-b3d4-5ab79903a34e', 'admin@soukelgomla.com', '87W3O7eBX2xKF5ZuxCneG6QgqwqC2wmeoNF46zFJad5clO4THumn471Ve9EDQJTe', 'System Owner', NULL, 'owner', NULL, '00000000-0000-0000-0000-000000000001', 1, '2026-08-09T12:17:47.179Z', '2026-08-09T12:17:47.179Z');

-- 2) Refresh the password/role whenever the script is re-run.
UPDATE profiles
SET password_hash = '87W3O7eBX2xKF5ZuxCneG6QgqwqC2wmeoNF46zFJad5clO4THumn471Ve9EDQJTe', role = 'owner', is_active = 1, updated_at = '2026-08-09T12:17:47.179Z', full_name = 'System Owner'
WHERE email = 'admin@soukelgomla.com';
