import type { Product, Order } from "./types";

export const logoUrl =
  "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ChatGPT%20Image%20Aug%206%2C%202026%2C%2001_59_41%20PM-XlqTPzN2O6W7ZSsRAbrdzcpshw4863.png";

/**
 * Build a reliable Unsplash image URL for a given photo id.
 * Centralizes sizing/quality tokens so every storefront image uses a
 * consistent, sharp, correctly-cropped rendering.
 */
function image(photoId: string, width = 600, height?: number): string {
  const h = height ? `&h=${height}` : "";
  return `https://images.unsplash.com/${photoId}?auto=format&fit=crop&w=${width}${h}&q=80`;
}

export const products: Product[] = [
  {
    id: "sugar",
    name: "سكر",
    english: "Sugar",
    size: "1 كيلو",
    retail: 27,
    wholesale: 24.5,
    category: "السكر والشاي والقهوة",
    inStock: true,
    image: image("photo-1558618666-fcd25c85cd64"),
  },
  {
    id: "tea",
    name: "شاي ليبتون",
    english: "Lipton Tea",
    size: "100 كيس",
    retail: 68,
    wholesale: 60,
    category: "السكر والشاي والقهوة",
    inStock: true,
    brand: "ليبتون",
    image: image("photo-1556742049-0cfed4f6a45d"),
  },
  {
    id: "coffee",
    name: "بن مطحون",
    english: "Ground Coffee",
    size: "250 جرام",
    retail: 95,
    wholesale: 82,
    category: "السكر والشاي والقهوة",
    inStock: true,
    oldPrice: 105,
    image: image("photo-1447933601403-0c6688de566e"),
  },
  {
    id: "oil",
    name: "زيت عباد الشمس",
    english: "Sunflower Oil",
    size: "1.8 لتر",
    retail: 72,
    wholesale: 65,
    category: "الزيوت",
    inStock: true,
    image: image("photo-1474979266404-7eaacbcd87c5"),
  },
  {
    id: "rice",
    name: "أرز بسمتي",
    english: "Basmati Rice",
    size: "1 كيلو",
    retail: 35,
    wholesale: 30,
    category: "الأرز والمكرونات",
    inStock: true,
    oldPrice: 38,
    image: image("photo-1586201375761-83865001e31c"),
  },
  {
    id: "pasta",
    name: "مكرونة",
    english: "Pasta",
    size: "500 جرام",
    retail: 18,
    wholesale: 15,
    category: "الأرز والمكرونات",
    inStock: true,
    image: image("photo-1551462147-ff29053bfc14"),
  },
  {
    id: "mozzarella",
    name: "موتزريلا",
    english: "Mozzarella",
    size: "500 جرام",
    retail: 85,
    wholesale: 75,
    category: "مشتقات الألبان",
    inStock: true,
    image: image("photo-1609167830220-7164aa360951"),
  },
  {
    id: "cheese",
    name: "جبنة بيضاء",
    english: "White Cheese",
    size: "500 جرام",
    retail: 55,
    wholesale: 48,
    category: "مشتقات الألبان",
    inStock: true,
    image: image("photo-1486297678162-eb2a19b0a32d"),
  },
  {
    id: "butter",
    name: "زبدة",
    english: "Butter",
    size: "250 جرام",
    retail: 42,
    wholesale: 36,
    category: "مشتقات الألبان",
    inStock: true,
    image: image("photo-1589985270826-4b7bb135bc9d"),
  },
  {
    id: "milk",
    name: "لبن مبستر",
    english: "Milk",
    size: "1 لتر",
    retail: 30,
    wholesale: 26,
    category: "مشتقات الألبان",
    inStock: true,
    image: image("photo-1550583724-b2692b85b150"),
  },
  {
    id: "spices",
    name: "بهارات مشكلة",
    english: "Mixed Spices",
    size: "100 جرام",
    retail: 25,
    wholesale: 20,
    category: "البهارات",
    inStock: true,
    image: image("photo-1596040033229-a9821ebd058d"),
  },
  {
    id: "tomatoSauce",
    name: "صلصة طماطم",
    english: "Tomato Sauce",
    size: "500 جرام",
    retail: 22,
    wholesale: 18,
    category: "الصلصات",
    inStock: true,
    image: image("photo-1556910103-1c02745aae4d"),
  },
  {
    id: "cannedTuna",
    name: "تونة معلبة",
    english: "Canned Tuna",
    size: "140 جرام",
    retail: 45,
    wholesale: 40,
    category: "المعلبات",
    inStock: true,
    image: image("photo-1584269600464-37b1b58a9fe7"),
  },
  {
    id: "biscuits",
    name: "بسكويت",
    english: "Biscuits",
    size: "400 جرام",
    retail: 15,
    wholesale: 12,
    category: "المخبوزات والبسكويت",
    inStock: true,
    oldPrice: 17,
    image: image("photo-1558961363-fa8fdf82db35"),
  },
  {
    id: "bread",
    name: "عيش فينو",
    english: "Bread",
    size: "100 جرام",
    retail: 5,
    wholesale: 4,
    category: "المخبوزات والبسكويت",
    inStock: true,
    image: image("photo-1509440159596-0249088772ff"),
  },
  {
    id: "water",
    name: "مياه معدنية",
    english: "Mineral Water",
    size: "1.5 لتر",
    retail: 8,
    wholesale: 6.5,
    category: "المياه والمرطبات",
    inStock: true,
    image: image("photo-1523362628745-0c100150b504"),
  },
  {
    id: "cola",
    name: "مشروب غازي",
    english: "Soft Drink",
    size: "1 لتر",
    retail: 18,
    wholesale: 15,
    category: "المياه والمرطبات",
    inStock: true,
    image: image("photo-1554866585-cd94860890b7"),
  },
  {
    id: "detergent",
    name: "مسحوق غسيل",
    english: "Detergent",
    size: "1 كيلو",
    retail: 40,
    wholesale: 34,
    category: "المنظفات",
    inStock: true,
    oldPrice: 45,
    image: image("photo-1585421514738-01798e348b17"),
  },
  {
    id: "babyWipes",
    name: "مناديل أطفال",
    english: "Baby Wipes",
    size: "80 منديل",
    retail: 20,
    wholesale: 16,
    category: "العناية بالطفل",
    inStock: true,
    image: image("photo-1555252333-9f8e92e65df9"),
  },
  {
    id: "tomatoes",
    name: "طماطم",
    english: "Tomatoes",
    size: "1 كيلو",
    retail: 12,
    wholesale: 10,
    category: "بالحبة",
    inStock: true,
    image: image("photo-1542838132-92c53300491e"),
  },
];

// ⚠️ These are DEMO highlight lists (not real best-seller rankings).
export const bestSellingIds = [
  "sugar",
  "oil",
  "rice",
  "mozzarella",
  "tea",
  "detergent",
];
export const recentlyAddedIds = [
  "cheese",
  "coffee",
  "milk",
  "biscuits",
  "water",
  "tomatoSauce",
];

export const orders: Order[] = [
  {
    id: "SG-10482",
    status: "delivered",
    date: "١٢ أغسطس ٢٠٢٦",
    total: 247,
    items: [
      { id: "sugar", quantity: 2 },
      { id: "oil", quantity: 1 },
      { id: "rice", quantity: 1 },
    ],
    address: "شارع التحرير، الدقي، الجيزة",
    delivery: "تم التسليم ١٢ أغسطس",
  },
  {
    id: "SG-10476",
    status: "preparing",
    date: "١١ أغسطس ٢٠٢٦",
    total: 185,
    items: [
      { id: "mozzarella", quantity: 1 },
      { id: "pasta", quantity: 2 },
    ],
    address: "شارع جامعة الدول، المهندسين، الجيزة",
    delivery: "متوقع الوصول اليوم",
  },
  {
    id: "SG-10451",
    status: "cancelled",
    date: "٨ أغسطس ٢٠٢٦",
    total: 132,
    items: [
      { id: "cheese", quantity: 1 },
      { id: "butter", quantity: 1 },
      { id: "tea", quantity: 1 },
    ],
    address: "شارع عباس العقاد، مدينة نصر، القاهرة",
    delivery: "تم الإلغاء",
  },
];

export const categories = [
  ["الكل", "✦"],
  ["بقالة", "▦"],
  ["مشروبات", "◒"],
  ["مجمدات", "❄"],
  ["تنظيف", "✧"],
  ["أطفال", "♧"],
  ["عناية شخصية", "◉"],
];
