export { roles, profiles, sessions, authAuditLogs } from '@/db/schema/auth'
export { branches } from '@/db/schema/branches'
export { categories, products, productMedia, categoryMedia, productTags } from '@/db/schema/catalog'
export type { ProductStatus, MediaResourceType } from '@/db/schema/catalog'
export { orders, orderItems, orderStatusHistory, orderTimeline } from '@/db/schema/orders'
export type { OrderStatus, OrderSource, PaymentMethod, PaymentStatus } from '@/db/schema/orders'
export { customers, customerAddresses } from '@/db/schema/customers'
export { offers } from '@/db/schema/offers'
export type { DiscountType, OfferStatus } from '@/db/schema/offers'
export { deliveryDrivers, deliveryAreas, deliveryAssignments } from '@/db/schema/delivery'
export type { DriverStatus, AssignmentStatus } from '@/db/schema/delivery'
export { inventoryMovements } from '@/db/schema/inventory'
export type { MovementType } from '@/db/schema/inventory'
export { suppliers, purchaseOrders, purchaseOrderItems } from '@/db/schema/suppliers'
export type { PurchaseOrderStatus } from '@/db/schema/suppliers'
export { returns, returnItems } from '@/db/schema/returns'
export type { ReturnStatus } from '@/db/schema/returns'
export { featureGroups, featureFlags } from '@/db/schema/featureFlags'
export { activityLogs, notifications, settings } from '@/db/schema/operations'
export type { NotificationSeverity } from '@/db/schema/operations'

export type { UserRole } from '@/db/schema/auth'
