#!/usr/bin/env node
/**
 * Create / update the first OWNER admin account for a D1 database.
 *
 * Cloudflare-compatible seed mechanism — no admin registration page exists by
 * design. Run this script on a development machine and apply the generated SQL
 * to D1 (local or remote) via Wrangler.
 *
 * Usage:
 *   SEED_ADMIN_EMAIL=owner@example.com SEED_ADMIN_PASSWORD='very-secret' pnpm seed:admin
 *
 * Options:
 *   --out <file>   write SQL to this path (default: drizzle/seed-admin.sql)
 *   --apply        also run `wrangler d1 execute DB --file=<path>` afterwards
 *
 * Requires Node 22.6+ (Web Crypto global + `--experimental-strip-types`).
 */

import { hashPassword } from '../src/lib/crypto.ts'

interface SeedOptions {
  email: string
  password: string
  fullName: string
  branchId: string | null
  outFile: string
  apply: boolean
}

function parseArgs(argv: string[]): Partial<SeedOptions> {
  const opts: Partial<SeedOptions> = { branchId: null }
  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i]
    if (arg === '--out') opts.outFile = argv[++i]
    else if (arg === '--apply') opts.apply = true
  }
  return opts
}

function escapeSql(value: string): string {
  return value.replace(/'/g, "''")
}

function help(): void {
  console.log(
    [
      'seed-admin — create/update the initial OWNER account',
      '',
      'Usage:',
      '  SEED_ADMIN_EMAIL=owner@example.com SEED_ADMIN_PASSWORD="secret" pnpm seed:admin',
      '',
      'Options:',
      '  --out <file>   output SQL file (default drizzle/seed-admin.sql)',
      '  --apply        run `wrangler d1 execute DB --file=<path>` after writing',
    ].join('\n')
  )
}

async function main(): Promise<void> {
  const email = process.env.SEED_ADMIN_EMAIL?.trim().toLowerCase()
  const password = process.env.SEED_ADMIN_PASSWORD
  const fullName = process.env.SEED_ADMIN_NAME?.trim() || 'System Owner'
  const args = parseArgs(process.argv.slice(2))

  if (!email || !password) {
    help()
    process.exitCode = 1
    return
  }
  if (password.length < 8) {
    console.error('Error: password must be at least 8 characters')
    process.exitCode = 1
    return
  }

  console.log(`Seed: hashing password for ${email} (PBKDF2-SHA256, 100k iterations)...`)
  const passwordHash = await hashPassword(password)

  const now = new Date().toISOString()
  const branchId = args.branchId ?? '00000000-0000-0000-0000-000000000001'
  const profileId = crypto.randomUUID()

  const sql = [
    '-- ============================================================',
    '-- Generated by scripts/seed-admin.ts — first OWNER account',
    '-- Apply with: wrangler d1 execute DB --file=<this file>',
    '-- ============================================================',
    '',
    '-- 1) Insert the account if the email does not exist yet.',
    `INSERT OR IGNORE INTO profiles (id, email, password_hash, full_name, phone, role, avatar, branch_id, is_active, created_at, updated_at)`,
    `VALUES ('${profileId}', '${escapeSql(email)}', '${passwordHash}', '${escapeSql(fullName)}', NULL, 'owner', NULL, '${branchId}', 1, '${now}', '${now}');`,
    '',
    '-- 2) Refresh the password/role whenever the script is re-run.',
    `UPDATE profiles`,
    `SET password_hash = '${passwordHash}', role = 'owner', is_active = 1, updated_at = '${now}', full_name = '${escapeSql(fullName)}'`,
    `WHERE email = '${escapeSql(email)}';`,
    '',
  ].join('\n')

  const outFile = args.outFile || 'drizzle/seed-admin.sql'
  const { writeFileSync } = await import('node:fs')
  writeFileSync(outFile, sql, 'utf8')
  console.log(`Seed: SQL written to ${outFile}`)

  if (args.apply) {
    const { execSync } = await import('node:child_process')
    console.log('Seed: applying to D1 (wrangler d1 execute DB)...')
    execSync(`wrangler d1 execute DB --file=${outFile}`, { stdio: 'inherit' })
  } else {
    console.log('Seed: done. Apply with:')
    console.log(`  wrangler d1 execute DB --local  --file=${outFile}`)
    console.log(`  wrangler d1 execute DB --remote --file=${outFile}`)
  }
}

void main()